export default {
	// Server URL
	SERVER_URL: 'YOUR_SERVER_URL',

	// Facebook
	APP_ID: 'YOUR_FACEBOOK_APP_ID',

	// Google
	CLIENT_ID_IOS: 'YOUR_GOOGLE_CLIENT_ID_IOS',
	CLIENT_ID_ANDROID: 'YOUR_GOOGLE_CLIENT_ID_ANDROID',

	// Maps API
	G_MAPS_API: 'YOUR_GOOGLE_MAPS_API_KEY',

	// AWS
	AWS_ACCESS_KEY: 'YOUR_AMAZON_ACCESS_KEY',
	AWS_SECRET_KEY: 'YOUR_AMAZON_SECRET_KEY'
}
